### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by cliffbueno** [rcedgar/usearch12_documentation#2]
Hi Robert,

Thank you for usearch! 

I was trying to view some examples and tutorials. I just discovered that all 8 links on this page https://rcedgar.github.io/usearch12_documentation/tutorials.html are broken. They give 404 not found. If those tutorials still exist, please update to the correct links.

Thanks,

Cliff

**Comment by rcedgar** [comment]
Sorry about that! You can find the tutorials here:

[https://drive5.com/usearch/manual/tutorials.html](https://drive5.com/usearch/manual/tutorials.html)

I'd be happy to accept a PR if you'd like to fix the links.

**Comment by cliffbueno** [comment]
Ok thanks. Or you could just add this one link to the documentation.
